CREATE TABLE [dbo].[Player]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [SSN] NVARCHAR(50) NOT NULL, 
    [FirsrName] NVARCHAR(100) NOT NULL, 
    [LastName] NVARCHAR(100) NOT NULL, 
    [TeamId] INT NULL, 
    [Phone] NVARCHAR(50) NULL, 
    [Email] NVARCHAR(2000) NULL
)
